language: java

jdk:
  - oraclejdk8
  - openjdk7

install: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - export TEST_MODE=TRAVIS
  - export EA_HOSTNAME=$AT_HOSTNAME
  - export EA_ENCRYPTION_KEY=$AT_ENCRYPTION_KEY
  - export EA_TRANSITION_KEY=$AT_TRANSITION_KEY
  - export EA_SALT=$AT_SALT
  - gradle test --info